### ISSUE TITLE
Формула пересчета

### ISSUE THREAD

**Issue by burrbull** [Tyill/SVisual#10]
Идея навеяна #9.
Думаю стоит добавить возможность ввода формулы, по которой можно будет, допустим,переводить из одних единиц измерения в другие (масштабировать значения), если это по какой-то причине невозможно на самом контроллере.

**Comment by Tyill** [comment]
не надо. все такие дела можно (и нужно) делать в контроллере.

**Comment by Tyill** [comment]
с формулой много возни, и мало кому нужно будет такой функционал. 
если он в МК не может формулу перевода написать, то там тоже не сможет

**Comment by Tyill** [comment]
так. еще подумал.
можно сделать виртуальные сигналы, то есть реальные сигналы не трогать, а дать возможность создавать новые сигналы. 
например, сумма/разность реальных, или просто клон реального инвертированный. 
или, например, виртуальный булевый, когда значение больше чем... и тд
вот это еще мбыть пригодится кому. 
(хотя на производстве за 7 лет ни разу не пригодились такие фишки ibaPDA).

**Comment by Tyill** [comment]
скрипты [завез](https://github.com/Tyill/SVisual/releases/tag/1.0.8). описание добавил в мануал.
