### ISSUE TITLE
Запуск теста на Arduino

### ISSUE THREAD

**Issue by Sundiverr** [Tyill/SVisual#12]
Здравствуйте! Не пойму, что я делаю не так: скетч правильный, загружается в МК, в SVMonitor прописан нужный COM-порт, но никаких модулей всё равно не появляется.
Помогите, пожалуйста!

**Comment by Tyill** [comment]
Здравствуйте.

> но никаких модулей всё равно не появляется
что значит никаких других? вообще нет модулей или есть какой-то не тот?
покажите скрин окна SVMonitor после того как подключили ардуино.

**Comment by Tyill** [comment]
Операционная система какая?

**Comment by Sundiverr** [comment]
![image](https://user-images.githubusercontent.com/50154618/57007732-9276e080-6bf3-11e9-8779-b58700df7ade.png)
![image](https://user-images.githubusercontent.com/50154618/57007755-bafeda80-6bf3-11e9-82bd-06aa45ef11c9.png)
Win10 x64
Arduino Leonardo

**Comment by Tyill** [comment]
Скорость передачи в ардуино по умолч 9600 стоит: 
`
bool connectOfCOM(const char* module, int speed = 9600);
` 
А в настройках SVMonitor не меняли?

**Comment by Tyill** [comment]
в клиенте для ардуино пользуюсь сторонним кодом - MsTimer2 для создания таймерных прерываний. 
посмотрел его и не увидел нигде "Leonardo", может быть он поддерживает такой тип контроллера.

проверьте сами этот код: 
`c:\cpp\SVisual\src\SVArduino\MsTimer2.cpp`

здесь можете пример работы с ним посмотреть: 
`http://arduino.net.ua/file_archive/Arduino%20Library/MsTimer2%20Library/`

**Comment by Tyill** [comment]
вот нашел на форуме, есть у людей проблема с либой MsTimer2 на "леонардо" как раз
`http://mypractic.ru/urok-10-preryvanie-po-tajmeru-v-arduino-biblioteka-mstimer2-parallelnye-processy.html#comment-3288`

**Comment by Sundiverr** [comment]
Спасибо, попробую, отпишусь о результате

**Comment by Sundiverr** [comment]
Пока немного не по теме скажу. В мануале тестовый код к Ардуино по крайней мере (остальные не проверял) остался видимо из старой версии, где ещё не было разделения переменных на Bool и Int, поэтому прописанные в нём функции не работают. 
И ещё, было бы здорово добавить к этому мануалу то, что библиотеку SVArduino надо поместить в папку с библиотеками самой Arduino IDE. Не исключаю, конечно, что это я такой недалёкий, а всем это действие очевидно, но узнал я о нём только здесь из обсуждений.
А так, проект классный безусловно, под мои цели как раз подходит.

**Comment by Sundiverr** [comment]
Итак, что я сделал.
1. Заменил MSTimer2.h и MSTimer2.cpp на FlexiTimer2.h и FlexiTimer2.cpp
2. Заменил в файле sv_client.cpp все MSTimer2 на FlexiTimer2, в том числе и в строке #include
3. Заменил папку с библиотеками SVArduino в Arduino IDE на папку с изменёнными библиотеками.
4. Подключил плату, скомпилировал скетч, загрузил скетч, успешно. Порты правильные, не менял
Итог: модулей нет, графиков соответственно тоже.
Есть предположение, что дело в том, что в функции FlexiTimer2::set использует параметр resolution, который по умолчанию, если его не писать равен 1ой мс
![image](https://user-images.githubusercontent.com/50154618/57010435-446ad880-6c05-11e9-859d-a18936a20e0f.png)
Надо ли изменить значение по умолчанию? Например, на 10мс?
Вот как выглядит эта строка сейчас в sv_client.cpp
![image](https://user-images.githubusercontent.com/50154618/57010466-83009300-6c05-11e9-9de4-cdf6423cb1b9.png)

**Comment by Tyill** [comment]
нет. resolution менять не надо, я так понимаю это просто время цикла внутреннего, через который он делает отсчет, те по мс добавляет к счетчику, и как досчитает до уставки (SV_CYCLEREC_MS = 100мс) вызовет пользователь функцию.

в общем вам надо как то проверить, что функцию он вызывает. 
Можно попробывать без SVMonitor запустить, и в ф-ии thrProc написать Serial.print("Hello") и посмотреть в Arduino IDE, будет ли писать.

**Comment by Tyill** [comment]
А еще. Закройте IDE после того как загрузили скетч, поскольку она может продолжать висеть на порте. Потом запускайте SVMonitor.

**Comment by Sundiverr** [comment]
Странно, после прописывания Serial.print("Hello") появился график

**Comment by Tyill** [comment]
да. странно. докопаться бы что там происходит..
на счет документации - если вы сами дополните что считаете нужным, то будет замечательно, тем самым внесете вклад так сказать, потому что в одну каску тяжело тянуть все.

**Comment by Sundiverr** [comment]
Хорошо, я возможно поработаю в этих направлениях
