### ISSUE TITLE
Баг при экспорте

### ISSUE THREAD

**Issue by Sivolday** [Tyill/SVisual#16]
![image](https://user-images.githubusercontent.com/30410315/62855238-e4afbd80-bd1b-11e9-9f80-603ab0170fd7.png)

При экспорте в независимости от выбора модуля, сигналы всегда для первого в списке. Невозможно осуществить экспорт сигналов для других модулей. 
[Пример файла сохранения](https://github.com/Tyill/SVisual/files/3491643/svrec_tempUTC7.zip)

**Comment by Tyill** [comment]
принято. поправлю в ближ время.

**Comment by Tyill** [comment]
[поправил](https://github.com/Tyill/SVisual/releases/tag/1.1.1)
