### ISSUE TITLE
usb com в linux

### ISSUE THREAD

**Issue by burrbull** [Tyill/SVisual#2]
Попробовал запустить Вашу программу в Ubuntu. Сборка для CentOS запустилась с полпинка.
Возникла проблема с выбором порта.
Возникает вопрос: COMx - это /dev/ttySx ?
И если так, то как подключить usb<->uart переходник, который определяется как /dev/ttyUSB0,
а при переподключении может еще и меняться номер ?

![default](https://user-images.githubusercontent.com/3072754/40986676-7b8ca06a-68ef-11e8-9576-12057bf96482.png)

![default](https://user-images.githubusercontent.com/3072754/40986620-5921d360-68ef-11e8-8c98-f030af349ac5.png)

**Comment by Tyill** [comment]
установите сначала ide для ардуино. и в ней попробуйте залить скетч через выбранный COM, (становится активен только когда подключаете устр-во). Потом уже пробуйте монитор. 
http://arduino.ru/Arduino_environment

**Comment by burrbull** [comment]
В Arduino Studio в **линуксе** порт также определяется как /dev/ttyUSB0. Никаких COM.
![default](https://user-images.githubusercontent.com/3072754/40990791-9a55a7f2-68fa-11e8-9c83-b286a75d684c.png)
Он должен появиться в программе?

**Comment by Tyill** [comment]
задайте адрес в svmonitor.ini

![screenshot from 2018-06-05 23-03-15](https://user-images.githubusercontent.com/16229799/40994281-4307a2fa-6915-11e8-926c-d17b4652c97e.png)

**Comment by burrbull** [comment]
Ясно. Спасибо.
