### ISSUE TITLE
Raspberri Pi3 Ubuntu Mate

### ISSUE THREAD

**Issue by dantistrc** [Tyill/SVisual#21]
Этот труд можно собрать под Raspberri Pi3 Ubuntu Mate?

**Comment by Tyill** [comment]
Ну слушайте, у меня нет Raspberri Pi, я не знаю, попробуйте. 
Еще есть вариант воспользоваться образом [Docker](https://hub.docker.com/r/tyiler/svdocker),
то есть запустить на Raspberri Pi в докере.

Как что получится-нет, напишите здесь потом.

**Comment by dantistrc** [comment]
А если я профинансирую проект нужный мне, возьметесь? Малинку и все что необходимо в подарок. Задача проста-2 аналоговых сигнала выводятся в график, по одному из них считается скорость изменения и выводится в виде цифр + абсолютное значение отображается стрелкой на вертикальной шкале. Ну и код мне , я немножко пишу поэтому остальное доделаю (нужны 2 цифровых выхода и два входа. Весь проект сделать мне трудно, проще заказать. Почему малина? Нужен дисплей , размеры и скорость загрузки тоже важны.

**Comment by dantistrc** [comment]
Под заказ пишите? совсем немного допилить. Малинку в подарок.

**Comment by Tyill** [comment]
напишите мне на почту al_medved@mail.ru:
-сроки, 
-подробности что надо сделать.
Там договоримся.

**Comment by almedvedevv** [comment]
> напишите мне на почту: -сроки, -подробности что надо сделать. Там договоримся.
