### ISSUE TITLE
При соединении Arduino по Ethernet не появляется модуль в SVMonitor.

### ISSUE THREAD

**Issue by Alex6305** [Tyill/SVisual#22]
Здравствуйте.
При соединении Arduino по Ethernet не появляется модуль в SVMonitor. По COM всё ok и в программе и в браузере. Пример скетча из мануала, только заменил connectOfCOM("test") на connectOfEthernet("test", (0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED), (127,0,0,1), (127,0,0,1), 2145). Ардуино MEGA2560 + miniW5100, Ethernet Shield проверял - работает. ОС – Win-7. Наверное, что-то я делаю не так, или что-то не делаю.... Помогите пожалуйста разобраться.
![Sketch](https://user-images.githubusercontent.com/60961110/74317079-c76fb080-4d8b-11ea-9ac1-ce607a787343.jpg)
![SVMonitor](https://user-images.githubusercontent.com/60961110/74317081-c8084700-4d8b-11ea-9999-3d91ff4355db.jpg)

**Comment by Tyill** [comment]
Здравствуйте.

 На скрине вижу что порт стоит 2145, а надо 2144

`connectOfEthernet(... int portServ)`

**Comment by Alex6305** [comment]
В скетче исправил, как Вы написали. В настройках программы ни чего не менял. Может быть нужно прописать IP, маска, шлюз, в свойствах сетевого адаптера?
![2144](https://user-images.githubusercontent.com/60961110/74340198-8b9e1080-4db6-11ea-8cda-b6d55a7a67eb.JPG)
![SVM](https://user-images.githubusercontent.com/60961110/74340286-b0928380-4db6-11ea-982d-33986e4862c6.JPG)
![Net](https://user-images.githubusercontent.com/60961110/74340319-c142f980-4db6-11ea-8d6a-92b14746cacb.JPG)

**Comment by Tyill** [comment]
> Может быть нужно прописать IP, маска, шлюз, в свойствах сетевого адаптера?
нет, здесь ничего не надо трогать.

Как то вы странно адреса передаете. И ip адреса дбыть разные у МК и ПК. 
Надо строки передавать:
`connectOfEthernet("test", "DE-AD-BE-EF-FE-ED", "127.0.0.2", "127.0.0.1", 2144)`

Так еще попробуйте:
`connectOfEthernet("test", "DE-AD-BE-EF-FE-ED", "192.168.1.2", "192.168.1.1", 2144)`

где (для примера) "192.168.1.1" - адрес вашего ПК, посмотрите в свойствах сетевого подключения.

Я к сожалению сейчас сам проверить не могу.

**Comment by Alex6305** [comment]
Большое спасибо за помощь. Второй вариант сработал.
![ethernet](https://user-images.githubusercontent.com/60961110/74365286-d2076580-4dde-11ea-899c-78175c28f8a3.JPG)

И если можно подскажите ещё, как каждому графику определить цвет, чтобы он не менялся после перезапуска программы. В скетче или в .ini файле или, например как на скриншоте.
![example](https://user-images.githubusercontent.com/60961110/74365353-fbc08c80-4dde-11ea-84a7-da6abfb700d6.JPG)

**Comment by Tyill** [comment]
> как каждому графику определить цвет, чтобы он не менялся после перезапуска программы.

такой возможности нет, к сожалению. 

Создайте новую задачу по этому поводу, я сделаю в свободное время.

**Comment by Alex6305** [comment]
Спасибо. Создал.
