### ISSUE TITLE
Цвет графика как атрибут сигнала, определяемый пользователем.

### ISSUE THREAD

**Issue by Alex6305** [Tyill/SVisual#23]
Программное обеспечение, такого рода как SVisual, не редко используется для работы с однотипными устройствами, у которых контролируют одни и те же сигналы. В случаях, когда их относительно не много, у пользователя цвет графика начинает ассоциироваться с наименованием сигнала. В результате и в реальном времени и при просмотре архива, как минимум нет необходимости отвлекаться на легенду. Можно было бы сделать цвет, таким же атрибутом сигнала, определяемым пользователем, как например Group или Comment. Ну, или каким либо иным образом. IMHO, эта опция пригодиться многим.
	Заранее спасибо.

**Comment by Tyill** [comment]
[готово](https://github.com/Tyill/SVisual/releases/tag/1.1.5)
