### ISSUE TITLE
Ошибки компиляции для платы Arduino Due

### ISSUE THREAD

**Issue by Alex6305** [Tyill/SVisual#24]
Здравствуйте.
Подскажите пожалуйста, как изменить sv_client.cpp при замене MsTimer2 на DueTimer.
Ошибки компиляции для платы Arduino Due:
sv_client.cpp:124:3: error: 'set' is not a member of 'DueTimer'
DueTimer::set(SV_CYCLEREC_MS, thrProc);
sv_client.cpp:125:19: error: cannot call member function 'DueTimer& DueTimer::start(long int)' without object
 DueTimer::start();

**Comment by Tyill** [comment]
Здравствуйте.

MsTimer2::set(SV_CYCLEREC_MS, thrProc);  
MsTimer2::start();

заменить на

 Timer0.attachInterrupt(thrProc).start(SV_CYCLEREC_MS);

**Comment by Alex6305** [comment]
Спасибо, заменил. Теперь скетч загружается успешно.  Но модуль в SVMonitor не появляется.
Может быть, ещё что-то нужно изменить при использовании другого таймера?

**Comment by Tyill** [comment]
Да вроде ничего больше не надо. 
Попробуйте поотлаживать так: напишите в функцию thrProc где-нидь Serial.print("Hello"), и запустите в Arduino IDE, то есть без подключения к SVMonitor. Тем самым проверите что функция отправки данных вызывается внутри по таймеру.
Потом можно дальше копать.

**Comment by Alex6305** [comment]
Не работает.
![Capture](https://user-images.githubusercontent.com/60961110/75578351-bb1a7180-5a74-11ea-86dc-889f19b27adf.JPG)
Хотя я не уверен, что написал правильно.

**Comment by Tyill** [comment]
Правильно все. 
Значит надо разбираться с DueTimer.

Попробуйте Timer1 сделать:
Timer1.attachInterrupt(thrProc).start(SV_CYCLEREC_MS);

Вот здесь у него есть примеры, посмотрите:
https://github.com/ivanseidel/DueTimer/tree/master/examples

В интернете еще поищите примеры с DueTimer.

**Comment by Tyill** [comment]
А. Нет. Неправильно.

Функция thrProc - это моя ф-я. 

Ее на править в https://github.com/Tyill/SVisual/blob/master/src/SVArduino/sv_client.cpp#L88

**Comment by Alex6305** [comment]
Только вечером смогу проверить.
Напишу, что получилось.
сб, 29 февр. 2020 г., 7:33 Alexander Medvedev <notifications@github.com>:

**Comment by Alex6305** [comment]
Попробовал Timer1 – ни чего не изменилось. А вот дальше:

Если
![1](https://user-images.githubusercontent.com/60961110/75614466-02befd00-5b4a-11ea-8add-cda339cb4ae9.JPG)
То
![1+](https://user-images.githubusercontent.com/60961110/75614471-179b9080-5b4a-11ea-9c69-9fa6cd2c5331.JPG)

А если
![2](https://user-images.githubusercontent.com/60961110/75614486-3c900380-5b4a-11ea-8c5a-b042946a9024.JPG)
То
![2+](https://user-images.githubusercontent.com/60961110/75614493-49145c00-5b4a-11ea-9717-506f9aa374df.JPG)

Может быть, МИЛЛИсекунды в MsTimer2 и МИКРОсекунды в DueTimer?

**Comment by Tyill** [comment]
Да, точно, там микросекунды: 
`To call a function handler every 1000 microseconds:`

Сделайте так тогда: 
Timer1.attachInterrupt(thrProc).start(SV_CYCLEREC_MS * 1000);

**Comment by Alex6305** [comment]
Сделал: "Timer1.attachInterrupt(thrProc).start(SV_CYCLEREC_MS * 1000);".
В мониторе порта "Hello" печатает, но в SVMonitor модуль не появляется.
Где-то что-то ещё не так.

**Comment by Tyill** [comment]
Проверьте еще раз как сейчас выглядит ф-я thrProc, когда вы работаете с SVMonitor. 
Должна выглядеть так: 
```
void thrProc (){
   objCln.doSendCycle();
}
```
То есть без всяких Serial.print(...), которые вы добавляли для проверки.

Можете файлы мне отправить, которые вы поменяли в SVArduino, я их посмотрю еще.

**Comment by Alex6305** [comment]
Да, вот папка из c:\Program Files (x86)\Arduino\libraries\

[SVArduino.zip](https://github.com/Tyill/SVisual/files/4273930/SVArduino.zip)

**Comment by Tyill** [comment]
Все правильно вроде. Должно работать все.

Можете попробовать в ArduinoIDE запустить, то есть без подключения к SVMonitor,
в Serial.print(...) ничего не надо писать.

Программа тестовая:
```#include <SVClient.h>
void setup() {

	bool ok = svisual::connectOfCOM("test");

}
int cnt = 0;
void loop() {

	svisual::addIntValue("dfv", cnt);

	++cnt;
	if (cnt > 10) cnt = 0;

	bool odd_cnt = cnt % 2;

    svisual::addBoolValue("bFW", odd_cnt);

    svisual::addBoolValue("bBW", !odd_cnt);

	delay(200);
}
```

Посмотрите монитора порта, должен показывать данные.

**Comment by Alex6305** [comment]
В мониторе порта ArduinoIDE только "=".

![test](https://user-images.githubusercontent.com/60961110/75671096-0f993900-5c8f-11ea-803a-8fe4ddb047c0.jpg)

**Comment by Tyill** [comment]
Тоже самое сделайте, только с MsTimer, то есть обратно на  MsTimer верните как было. 
Посмотрим.

**Comment by Alex6305** [comment]
К сожалению MsTimer2 не работает с AVR контроллером.
![MsTimer2](https://user-images.githubusercontent.com/60961110/75674538-5179ad80-5c96-11ea-907f-8da47edd0338.jpg)
#error Unsupported CPU type
#error MsTimer2 library only works on AVR architecture

**Comment by Alex6305** [comment]
То есть наоборот работает только с AVR, а Due ARM.

**Comment by Tyill** [comment]
Ладно тогда с этим MsTimer.
 
Я помню что писал в монитор, когда данные передавал. 
Сейчас значит ничего не пишет.
Дальше надо значит отладочные сообщения писать в каждую функцию, которая должна вызываться, таким образом: 

```
void thrProc(){
   Serial.print("thrProc")


void sv_client::doSendCyc(){
    Serial.print("sv_client::doSendCyc")


bool sv_client::sendData(){
   Serial.print("sv_client::sendData")

bool sv_client::sendDataOfCom(){
   Serial.print("sv_client::sendDataOfCom")

```

То есть надо понять где затык, потом из-за чего.

**Comment by Alex6305** [comment]
Отладочные сообщения добавил в функции. В результате в мониторе:
thrProcsv_client::doSendCycthrProcsv_client::doSendCycthrProcsv_client::doSendCycthrProcsv_client::doSendCycthrProcsv_client::doSendCycthrProcsv_client::doSendCycthrProcsv_client::doSendCycthrProcsv_client::doSendCycthrProcsv_client::doSendCyct
![monitor](https://user-images.githubusercontent.com/60961110/75678075-d7e5bd80-5c9d-11ea-981c-1f0344726fe1.jpg)

**Comment by Tyill** [comment]
вот видите, нет sv_client::sendData().

Уберите все отладоч сообщения, чтобы не мешали.
Дальше ставьте отладочные сообщения в ф-ии sv_client::sendData(), например здесь:

```
 void sv_client::doSendCyc(){
	   
	  // connection support
	  if (!isConnect_)
		  isConnect_ = tcpConnect();
	
Serial.print("isConnect = ");Serial.print(isConnect); Serial.print("\n");

	  // check active value in current cycle
	  int prevCyc = curCycCnt_ - 1; if (prevCyc < 0) prevCyc = SV_PACKETSZ - 1;
	  int sz = values_.size(); valueRec* vr;
	  for (int i = 0; i < sz; ++i){

		  vr = (valueRec*)values_.at(i);

		  if (!vr->isActive){
			  vr->vals[curCycCnt_] = vr->vals[prevCyc];

			  if ((vr->type == valueType::tBool) && vr->isOnlyFront)
				  vr->vals[curCycCnt_].tBool = false;
		  }

		  vr->isActive = false;
	  }

	  int next = curCycCnt_ + 1;
 
Serial.print("next = "); Serial.print(next); Serial.print("\n");

	  // send data
	  if (next >= SV_PACKETSZ) {

Serial.print("beforeSendData"); Serial.print("\n");

		  isConnect_ = (isConnect_) ? sendData() : false;

		  curCycCnt_ = 0;
	  }
	  else 
		  ++curCycCnt_; 
	 
	}


```

**Comment by Alex6305** [comment]
Поскольку "sv_client.cpp:339:44: error: 'isConnect' was not declared in this scope",
Заменил  "Serial.print("isConnect = ");Serial.print(isConnect); Serial.print("\n");"
на "Serial.print("isConnect_ = ");Serial.print(isConnect_); Serial.print("\n");".
В результате:
![isConnect](https://user-images.githubusercontent.com/60961110/75697017-8d743900-5cbd-11ea-852e-63726476111a.jpg)

**Comment by Tyill** [comment]
После "Serial.print("next = "); Serial.print(next); Serial.print("\n");"
напишите еще:
Serial.print("SV_PACKETSZ= "); Serial.print(SV_PACKETSZ); Serial.print("\n");

Дальше. Сюда поставьте запись:
```
  bool sv_client::sendData(){
      Serial.print("sendData");
    bool ok = isCom_ ? sendDataOfCom() : sendDataOfEthernet();
      
	return ok; 
  }
```

И сюда: 
```
bool sv_client::sendDataOfCom(){
      Serial.print("sv_client::sendDataOfCom");


}
```

**Comment by Alex6305** [comment]
Добавил записи, может быть, посмотрите файл, насколько правильно.


[sv_client.zip](https://github.com/Tyill/SVisual/files/4279369/sv_client.zip)

![Capture](https://user-images.githubusercontent.com/60961110/75745444-64d55900-5d28-11ea-88af-c41bb8e1076e.JPG)

**Comment by Tyill** [comment]
Да все правильно. Дальше то что пишет после "next = 9"? 
Вы понимаете что мы делаем?

Мы пытаемся понять, почему не заходит в функцию sendDataOfCom, соответственно не передает данные.

**Comment by Alex6305** [comment]
> Дальше то что пишет после "next = 9"?

На этом останавливается.

> Вы понимаете что мы делаем?

Пытаюсь вникнуть, но без Вашей помощи я с этим не разберусь.

**Comment by Alex6305** [comment]
Должно быть так:

isConnect_ = 1
next = 9
SV_PACKETSZ= 10
isConnect_ = 1
next = 10
SV_PACKETSZ= 10
beforeSendData
sendDatasv_client::sendDataOfCom=begin=

Но останавливается на:

isConnect_ = 1
next = 9
SV_PACKETSZ= 10
i

По аналогии с тестом "Hello", когда печатает только первые две буквы "He" и останавливается.
Может с этим таймером нужно как-то по-другому?..

**Comment by Tyill** [comment]
Давайте еще одну вещь проверим, сделайте так:
```
void sv_client::doSendCyc(){
	   
         Serial.print("sv_client::doSendCyc\n");

         return ;   

	  // connection support
	  if (!isConnect_)
	  .
          .
          .
}
```
 Подсчитаем сколько раз выведет "sv_client::doSendCyc" прежде чем заткнется. 
 Если заткнется, значит таймер считает только до 10, хотя не должен так работать.

**Comment by Alex6305** [comment]
Не затыкается. Что-то другое.

![Capture](https://user-images.githubusercontent.com/60961110/75794358-bd851000-5d81-11ea-85d4-74d53cf4a98e.JPG)

**Comment by Tyill** [comment]
Замените: 
```
// send data
	  if (next >= SV_PACKETSZ) {

Serial.print("beforeSendData"); Serial.print("\n");

		  isConnect_ = (isConnect_) ? sendData() : false;

		  curCycCnt_ = 0;
	  }
	  else 
		  ++curCycCnt_; 
```

на 

```
// send data
	  if (next >= SV_PACKETSZ) {

Serial.print("beforeSendData"); Serial.print("\n");

		 if (isCom_)
                     sendDataOfCom();
                 else 
                     sendDataOfEthernet();

		  curCycCnt_ = 0;
	  }
	  else 
		  ++curCycCnt_; 
```

Дальше здесь, закомментируйте "Serial.flush();": 

```
bool sv_client::sendDataOfCom(){

Serial.print("sv_client::sendDataOfCom");
      
	int sz = values_.size();
	
	if (sz == 0) return true;
	
	Serial.flush();
		
	const char* start = "=begin=";
.
.
.
```

**Comment by Alex6305** [comment]
Вот что получается:
![Capture](https://user-images.githubusercontent.com/60961110/75805578-2628b880-5d93-11ea-83d0-ded951530180.JPG)

[sv_client.zip](https://github.com/Tyill/SVisual/files/4282873/sv_client.zip)

**Comment by Tyill** [comment]
вы это уберите, иначе не идет дальше: 
```
void sv_client::doSendCyc(){
	   
         //Serial.print("sv_client::doSendCyc\n");

         //return ;   
```

**Comment by Alex6305** [comment]
Убрал.

![Capture](https://user-images.githubusercontent.com/60961110/75844165-43d33d80-5de6-11ea-8f7d-f7105e114b44.JPG)

**Comment by Tyill** [comment]
покажите файл sv_client.cpp

**Comment by Alex6305** [comment]
К сожалению, смогу только вечером.


ср, 4 мар. 2020 г., 7:40 Alexander Medvedev <notifications@github.com>:

**Comment by Alex6305** [comment]
[sv_client.zip](https://github.com/Tyill/SVisual/files/4288814/sv_client.zip)

**Comment by Tyill** [comment]
[sv_client.zip](https://github.com/Tyill/SVisual/files/4288849/sv_client.zip)

**Comment by Alex6305** [comment]
Вот что получается:


![monitor](https://user-images.githubusercontent.com/60961110/75910603-327a4780-5e5f-11ea-8cb6-784580e38e61.jpg)

**Comment by Tyill** [comment]
[sv_client.zip](https://github.com/Tyill/SVisual/files/4290716/sv_client.zip)

идем дальше.

**Comment by Alex6305** [comment]
Сейчас:
![2](https://user-images.githubusercontent.com/60961110/75947034-020ec980-5eb0-11ea-9350-3c9207c972d7.JPG)

**Comment by Tyill** [comment]
[sv_client.zip](https://github.com/Tyill/SVisual/files/4291199/sv_client.zip)

дальше. что напишет - сюда.

**Comment by Alex6305** [comment]
Не пишет, только "=". 
К сожалению, не было возможности проверить раньше.

![Capture](https://user-images.githubusercontent.com/60961110/76056251-2689a500-5f87-11ea-8392-7ed9535b057a.JPG)

**Comment by Tyill** [comment]
[sv_client.zip](https://github.com/Tyill/SVisual/files/4297051/sv_client.zip)

дальше.

**Comment by Alex6305** [comment]
![test](https://user-images.githubusercontent.com/60961110/76062554-fba74d00-5f96-11ea-82e2-5276aed0891e.jpg)

**Comment by Tyill** [comment]
[sv_client.zip](https://github.com/Tyill/SVisual/files/4297785/sv_client.zip)

дальше.

**Comment by Alex6305** [comment]
![Capture](https://user-images.githubusercontent.com/60961110/76075795-ae36da00-5fae-11ea-8fdf-5a0dd38d994b.JPG)

**Comment by Tyill** [comment]
Замените 

```
  bool sv_client::connectOfCOM(const char* moduleName, int speed){
  		
.
.
.
		Serial.begin(speed);   ->  Serial3.begin(speed); 

```

**Comment by Tyill** [comment]
Если не пойдет еще так попробуйте: 

```
bool sv_client::connectOfCOM(const char* moduleName, int speed){
  		
.
.
.
		Serial.begin(speed); 
                SerialUSB.begin(speed); 
```

**Comment by Alex6305** [comment]
Первый вариант – ошибка компиляции.
А второй однократно печатает "=".
[sv_client.zip](https://github.com/Tyill/SVisual/files/4297929/sv_client.zip)

**Comment by Tyill** [comment]
[sv_client.zip](https://github.com/Tyill/SVisual/files/4298213/sv_client.zip)

пробуйте так.

**Comment by Alex6305** [comment]
То же самое, только  "=".

**Comment by Tyill** [comment]
[sv_client.zip](https://github.com/Tyill/SVisual/files/4298290/sv_client.zip)

еще раз.

**Comment by Tyill** [comment]
[sv_client.zip](https://github.com/Tyill/SVisual/files/4298295/sv_client.zip)

поправил. предыд-й с ошибкой.

**Comment by Alex6305** [comment]
Не получается:

\sv_client.cpp:311:35: error: no matching function for call to 'UARTClass::write(svisual::valueType&, int)'
Serial.write(data->type, 4);

\sv_client.cpp:316:47: error: call of overloaded 'write(int&, int)' is ambiguous
 Serial.write(data->vals[j].tInt, 4);

\sv_client.cpp:318:49: error: no matching function for call to 'UARTClass::write(float&, int)'
Serial.write(data->vals[j].tFloat, 4);

\sv_client.cpp:325:12: error: 'pAuxSD' was not declared in this scope
delete pAuxSD;

**Comment by Tyill** [comment]
[sv_client.zip](https://github.com/Tyill/SVisual/files/4298367/sv_client.zip)

так.

**Comment by Alex6305** [comment]
Эти ошибки остались:

\sv_client.cpp:311:35: error: no matching function for call to 'UARTClass::write(svisual::valueType&, int)'
Serial.write(data->type, 4);

\sv_client.cpp:316:47: error: call of overloaded 'write(int&, int)' is ambiguous
Serial.write(data->vals[j].tInt, 4);

\sv_client.cpp:318:49: error: no matching function for call to 'UARTClass::write(float&, int)'
Serial.write(data->vals[j].tFloat, 4);

**Comment by Tyill** [comment]
[sv_client.zip](https://github.com/Tyill/SVisual/files/4298375/sv_client.zip)

**Comment by Alex6305** [comment]
То же самое:  "=".

**Comment by Alex6305** [comment]
Только: "=".

**Comment by Tyill** [comment]
Попробуйте увеличить размер внутреннего буфера, подробнее о нем тут
http://mypractic-forum.ru/viewtopic.php?t=11     

поставьте 256 байт:
#define SERIAL_TX_BUFFER_SIZE 256
#define SERIAL_RX_BUFFER_SIZE 256

**Comment by Alex6305** [comment]
Поставил 256.
![256](https://user-images.githubusercontent.com/60961110/76087133-93705f80-5fc6-11ea-8d04-4dc6308fa451.JPG)
[HardwareSerial.zip](https://github.com/Tyill/SVisual/files/4298479/HardwareSerial.zip)
[sv_client.zip](https://github.com/Tyill/SVisual/files/4298482/sv_client.zip)

![4](https://user-images.githubusercontent.com/60961110/76087182-ae42d400-5fc6-11ea-8580-a0f00efb14f2.JPG)

**Comment by Alex6305** [comment]
Не могу оценить, насколько это проще, но может быть попробовать подойти с другой стороны, адаптировать DueTimer к SVMonitor?

**Comment by Tyill** [comment]
DueTimer не причем. 
Здесь я думаю буфер переполняется (в который Serial.write пишет перед физической отправкой).

Попробуйте, еще пример сократить, только 1 переменную записывать: 

```
#include <SVClient.h>
void setup() {

	bool ok = svisual::connectOfCOM("test");

}
int cnt = 0;
void loop() {

	svisual::addIntValue("dfv", cnt);

	++cnt;
	if (cnt > 10) cnt = 0;

	bool odd_cnt = cnt % 2;
 
	delay(200);
}

```

**Comment by Tyill** [comment]
еще мне обратно вышлите sv_client.cpp, который у вас актуальный сейчас, я просто проверю что не запутались.

**Comment by Alex6305** [comment]
С одной переменной заработало.


![monitor](https://user-images.githubusercontent.com/60961110/76103215-5dd96f80-5fe2-11ea-8736-eaa53a778df6.JPG)

![SVM](https://user-images.githubusercontent.com/60961110/76103237-67fb6e00-5fe2-11ea-97f6-268fea280828.JPG)

**Comment by Tyill** [comment]
ну вот и хорошо. 
попробуйте буфер увеличить еще до 1024. И 3 переменные как в исходном примере записать.

**Comment by Alex6305** [comment]
Буфер увеличил, так как на скриншоте.
![BS](https://user-images.githubusercontent.com/60961110/76104900-333ce600-5fe5-11ea-8fd2-c01746fdf08a.JPG)

С тремя не работает, с двумя тоже.
![3](https://user-images.githubusercontent.com/60961110/76104965-4b146a00-5fe5-11ea-9cb7-708fa8f7a46d.JPG)
![2](https://user-images.githubusercontent.com/60961110/76104981-5071b480-5fe5-11ea-8ee4-f47a6e7026ab.JPG)

**Comment by Tyill** [comment]
значит не в буфере дело, да он и настройки общие поди для всех мк. 
обратно верните настройки по буферу, которые были (выше скрин был с ними).

Такой вопрос, вы когда грузите скетч, он же пишет сколько памяти осталось в мк. 
Посмотрите, может впритык. Скрин сделайте.

**Comment by Alex6305** [comment]
Настройки буфера вернул, память использует только 6%.

![6](https://user-images.githubusercontent.com/60961110/76137043-7d57b300-6049-11ea-97c9-7353c309273c.JPG)

**Comment by Alex6305** [comment]
Может быть дело в разной разрядности Mega и Due?
![99](https://user-images.githubusercontent.com/60961110/76137918-530af300-6053-11ea-8fc4-cc2d6b887136.JPG)

**Comment by Tyill** [comment]
Посмотрите сколько напишет: 

#include <SVClient.h>
void setup() {


}
void loop() {

        Serial.print("int sz "); Serial.print(sizeof(int)); Serial.print("\n");
        Serial.print("long int sz "); Serial.print(sizeof(long int)); Serial.print("\n");
	delay(200);
}

**Comment by Alex6305** [comment]
Пишет четыре.

![4](https://user-images.githubusercontent.com/60961110/76144340-4fe22800-6090-11ea-86f9-82d4425a6b29.JPG)

**Comment by Tyill** [comment]
Посмотрел еще раз код. 
Ну, не вижу где это (int32) могло повлиять. Везде правильно указываю размеры, когда вызываю Serial.write.

Так. Давайте попробуем отказаться от DuoTimer. Вручную если будете передавать данные, добавил для этого метод 'manualSendData':

```
void setup() {
	
}

int cnt = 0;
void loop() {

	svisual::addIntValue("dfv", cnt);

	++cnt;
	if (cnt > 10) cnt = 0;

	bool odd_cnt = cnt % 2;

    svisual::addBoolValue("bFW", odd_cnt);

    svisual::addBoolValue("bBW", !odd_cnt);


    svisual::manualSendData();

    delay(SV_CYCLEREC_MS);
}

```
[sv_client.zip](https://github.com/Tyill/SVisual/files/4301913/sv_client.zip)

**Comment by Alex6305** [comment]
Без таймеров наконец-то заработало, тест во всяком случае.
Попробую Ethernet, и уменьшить SV_CYCLEREC_MS, нужно ли при это изменять  SV_PACKETSZ?

![svm](https://user-images.githubusercontent.com/60961110/76145928-4d3aff00-609f-11ea-8025-6b0f1a320cc0.JPG)

**Comment by Tyill** [comment]
Отлично. 
Какой можно вывод сделать из всей этой эпопеи - пока думаю, что все таки dueTimer что-то там неправильно работает.

> SV_CYCLEREC_MS, нужно ли при это изменять SV_PACKETSZ
нет, они между собой не связаны.

**Comment by Alex6305** [comment]
БОЛЬШОЕ СПАСИБО ЗА ПОМОЩЬ.

Если не трудно, расскажите, пожалуйте более подробно о "SV_PACKETSZ" (размер пакета, как я понимаю).

В зависимости от чего нужно изменять и как он коррелируется с количеством  переменных.

В моём, конкретном случае, это 12 целочисленных (10bit) и 18 булевых.

"SV_CYCLEREC_MS" при этом желательно - 1MS, 10 – приемлемо, ну а 100 край.

**Comment by Tyill** [comment]
SV_PACKETSZ зачем вообще нужен. Этот параметр задает **количество** значений переменной, которое за раз передается на сервер (SVMonitor). Это разгружает линию передачи, иначе бы пришлось передавать каждое значение каждой переменной.

SV_PACKETSZ может принимать значения от 1 до ... какого-то приемлемого значения. Чем больше, тем больший буфер будет в памяти МК для каждой переменной, например, SV_PACKETSZ  = 10, значит буфер в МК для переменной 4 * 10 = 40 байт.

SV_CYCLEREC_MS может принимать значения от 10 мс. 
То есть 10 мс это принятый мной минимум (ограничение зашито в SVMonitor).
Потому что, если ниже ставить, то точность времени записи плывет (потому что ПК - это не система реального времени) и архив записей на диске начинает занимать гигабайты.

**Comment by Tyill** [comment]
В вашем случае можно не трогать SV_CYCLEREC_MS, оставить по умолчанию (100мс).

А цикл опроса датчиков, сделать 1мс. 

Получится так:

```
vaoid setup() {
	svisual::connectOfCOM("test");
}

int sendCnt = 0;
int cnt = 0;
void loop() {

	svisual::addIntValue("dfv", cnt);

	++cnt;
	if (cnt > 10) cnt = 0;

	bool odd_cnt = cnt % 2;

    svisual::addBoolValue("bFW", odd_cnt);

    svisual::addBoolValue("bBW", !odd_cnt);

    if ((sendCnt % SV_CYCLEREC_MS) == 0) 
       svisual::manualSendData();

    ++sendCnt;
    
    delay(1);
}

```

**Comment by Alex6305** [comment]
Понял. Спасибо.

пн, 9 мар. 2020 г., 7:42 Alexander Medvedev <notifications@github.com>:
