### ISSUE TITLE
SVisual Client in C not C++

### ISSUE THREAD

**Issue by Canonius** [Tyill/SVisual#26]
Hello,
i am very interesting in your application, but i try to write code for the STM32F4 controller in C without success.

Is it possible to write also an example code in C?

I am caching 64 values of thermocouples and then i want to send them over CAN and USB (to Svisual)
So i dont need the array of last 10 values in the "vals". i want to send 64 float signals (name+value) straigt to the svisual.

signals are stored for example into inputs[0 ... 63].temperature as float

please help me out how to use your protocol

```
typedef struct {
	float temperature;
	float current;
	float voltage;
	float flow;
	uint32_t average;
	type_t type;
} input_t;

typedef struct {
	char name[SV_NAMESZ];
	long int type; // tBool = 0, tInt = 1, tFloat = 2
	long int vals[SV_PACKETSZ]; // values data of 1 sec
} dataRef;
	
while (1) {
		measuring = TRUE; //interrupt enable
		get_inputs();
		measuring = FALSE; //interrupt disable

		print_inputs(CAN);
		print_inputs(USB);  // < this to SVisual
		HAL_Delay(1000);
	}

void print_inputs(uint8_t interface) {
   if(interface == CAN) {
   ...
   }

   if (interface == USB) {

		send_USB(start, strlen(start));

		int sz = 1; //normally CH_MAX = 64

		int vlSz = sizeof(dataRef);
		long int allSz = SV_NAMESZ + vlSz * sz;


		send_USB((char*) &allSz, 4);

		send_USB((char*)"TC2CAN", SV_NAMESZ);

		dataRef TXdata[1]; // normally TXdata[CH_MAX] = 64

		for (int i = 0; i < sz; ++i) {
			TXdata[i].type=(long int)2; //tBool = 0, tInt = 1, tFloat = 2
			memcpy(TXdata[i].name , "CH1_Temp", sizeof(SV_NAMESZ));
			memcpy(TXdata[i].vals , (long int)1234, sizeof(SV_PACKETSZ));
			send_USB(TXdata[i], sizeof(TXdata[i]));
		}

		send_USB("=end=", strlen("=end="));
	}
}

**Comment by Canonius** [comment]
ok i got it running....
![image](https://user-images.githubusercontent.com/50411138/78035416-5d29c400-7369-11ea-97a2-7bbca8550bfd.png)

but anyways, i and others would appreciate it, if you would offer also a library or example code in pure C.

Thanks for the great tool, i looked around but there is absolutely nothing comparable to yours!!!

Best regards!

**Comment by Tyill** [comment]
Hello. 
Here is the easiest client I can come up with:

```cpp
#define SV_CYCLEREC_MS 100 
#define SV_PACKETSZ 10
#define SV_NAMESZ 24

#include <stdlib.h>

int main(int args, char** args){

  // buffers for user sersors
  int32_t bufSensorOne[SV_PACKETSZ],
  	  bufSensorTwo[SV_PACKETSZ]
  	  bufSensorThree[SV_PACKETSZ];
  
  int cycCnt = 0,
      packCSz = 0;
  
  // main cycle
  while(true){ 
  
    if (cycCnt % SV_CYCLEREC_MS == 0){
     
      // read sensors value	   
      bufSensorOne[packCSz] = readSensor(addrSens1);
      bufSensorTwo[packCSz] = readSensor(addrSens2);
      bufSensorThree[packCSz] = readSensor(addrSens3);
      
      ++packCSz;
      
      // send data
      if (packCSz == SV_PACKETSZ){
  	 		
  	  int intSz = 4;
	 
  	  //           val name      val type     // buff vals
  	  int valSz = SV_NAMESZ   +   intSz  +  intSz * SV_PACKETSZ; 
  	  
  	  //         module name    
  	  int allSz = SV_NAMESZ  +  valSz * 3;  // 3 - number of variables
      
      
  	  const char* start = "=begin=";
  	  Serial.write(start, strlen(start));
      
  	  Serial.write((char*)&allSz, 4);
  	 	
  	  Serial.write("myDevice", SV_NAMESZ);
  	 
  	 
  	  // send name of sensorOne  
  	  Serial.write("sensor1", SV_NAMESZ);
  	  
  	  // send type of sensorOne  
  	  Serial.write(1, intSz);		    // 0 - bool, 1 - int, 2 - float
	 
  	  // send data of sensorOne  
  	  Serial.write(bufSensorOne, intSz * SV_PACKETSZ);
  	  
  	  
  	  // same for sensor2
  	  Serial.write("sensor2", SV_NAMESZ);
  	  Serial.write(1, intSz);
  	  Serial.write(bufSensorTwo, intSz * SV_PACKETSZ);
	 
	 
  	  // same for sensor3
  	  Serial.write("sensor3", SV_NAMESZ);
  	  Serial.write(1, intSz);
  	  Serial.write(bufSensorThree, intSz * SV_PACKETSZ);
  	
  	
  	  const char* end = "=end=";
  	  Serial.write(end, strlen(end));
  			
  	
  	  packCSz = 0;
    }
    
    ++cycCnt;
  } 
}

```

**Comment by Canonius** [comment]
Hello Alexander,
thank you so much for that example!

I used yesterday the first time your application in "real environment/measurement session".

Therefore i have some proposals for SVMonitor.

1. Manual scale of the Y-axis, like right-mouse-click on Y-axis to define the visual range. eg -40(°C) ... 150(°C)

2. Meaningful separation of the y-axis. You see in the picture i have only two y-marker (17 and 117).
i would expect to have it in 5-steps / 10-steps, for example 0, 5 , 10 ,15 .... or 0, 10, 20, 30, ....
![image](https://user-images.githubusercontent.com/50411138/78217490-8313ad80-74bc-11ea-8b42-98f9c1d82cf2.png)

3. Somehow a possibility to overwrite the signal names + add offset. (nice to have feature)
-> i did it with lua script (read value+time, add offset, change name), LUA is very important & useful feature!

I would really appreciate your support!

best regards!

**Comment by Tyill** [comment]
Hello.
Ok. Create a new issue and copy their proposals.
