### ISSUE TITLE
Proposals for improvement of SVMonitor

### ISSUE THREAD

**Issue by Canonius** [Tyill/SVisual#27]
Hello Alexander,

I used yesterday the first time your application in "real environment/measurement session".

Therefore i have some proposals for SVMonitor.

1. Manual scale of the Y-axis, like right-mouse-click on Y-axis (or separate Graph-Settings entry) to define the visual range. eg -40(°C) ... 150(°C)

2. Meaningful separation of the y-axis. You see in the picture i have only two y-marker (17 and 113).
i would expect to have it in 5-steps / 10-steps, for example 0, 5 , 10 ,15 .... or 0, 10, 20, 30, ....
image
![image](https://user-images.githubusercontent.com/50411138/78260464-49fc2d00-74fe-11ea-8a38-71ea86af3ab7.png)

3. Somehow a possibility to overwrite the signal names + add offset. (nice to have feature)
-> i did it with lua script (read value+time, add offset, change name), LUA is very important & useful feature!

I would really appreciate your support!

best regards!

**Comment by Tyill** [comment]
https://github.com/Tyill/SVisual/releases/tag/1.1.6
