### ISSUE TITLE
Клиент для embedded-hal

### ISSUE THREAD

**Issue by burrbull** [Tyill/SVisual#3]
Пытаюсь переписать ардуиновский клиент на rust для stm32.

Просьба уточнить, правильно ли я представляю структуру пакета?

![svformat](https://user-images.githubusercontent.com/3072754/46579217-93f17900-ca15-11e8-849f-8326fabcf30c.png)

**Comment by Tyill** [comment]
да. все верно. 

        int SINT = sizeof(int), vlSz = SV_NAMESZ + SINT + SINT * SV_PACKETSZ;

	int dataSz = SV_NAMESZ + vlSz * values_.size();

	int startSz = 7, endSz = 5;
	int allSz = startSz + SINT + dataSz + endSz;
                                          | 
                                   size dataSz

**Comment by burrbull** [comment]
Кое-что получилось [svisual-stm32f1](https://github.com/burrbull/svisual-stm32f1) и даже работает.
Но есть еще ряд вопросов, например по размеру пакета:
- строго 10 элементов или может меняться? 
- что, если для одной переменной нужно передать больше значений, а для другой меньше, я так понимаю это не возможно?

Отдельно хотелка по интерфейсу. Хотелось бы больше возможностей по масштабированию графика по амплитуде: возможность жестко задать значения min, max, и чтобы деления шкалы хотя бы немного округлялись.

**Comment by Tyill** [comment]
svisual-stm32f1, если работает, то перетаскивайте в основную ветку через pull request, - папку создайте в [исходниках  ](https://github.com/Tyill/SVisual/tree/master/src) с названием своего клиента.

1. Да, можно изменить. В мануале в приложении 7 об этом написано подробно.
2. Это невозможно. И это правильно, не нужно пользователю следить за этим и думать об этом.  
Польз-ль в своем основном рабочем цикле записываете столько значений сколько хочет(может), например, может вообще писать раз в минуту, а отправлять будет старые значения каждую секунду, или наоборот, - пишет хоть каждый цикл, а запишется только каждые 10 знач в сек.
Ну и естественно переменные между собой не связаны никак, те какое-то значение польз-ль может писать часто, какое-то редко, для него ничего не меняется.

По интерфейсу на счет амплитуды. Правильно понял, что автомасшаб-ие по амплитуде на опцию посадить, и если не активно, то по задан порогам масштабировать?

**Comment by burrbull** [comment]
В мануале. А слона то я и упустил.

На счет амплитуды. Автомасштабирование вещь хорошая и нужная, но когда шкала нормаль не отградуирована и скачет, трудно анализировать график. Поэтому да, нужно как-то фиксировать.

По поводу репы, я конечно могу сделать pull request, но во-первых еще не решены пару моментов, как [этот](https://github.com/japaric/heapless/issues/57) например, в общем нужно посоветоваться с гуру.
А во-вторых, что более важно, это бессмысленно. В расте репозиторий является одновременно и библиотекой, которая вытаскивается автоматом из инета как зависимость. В общем нужно соблюдать определенную структуру, а не просто "создать папку".

> пишет хоть каждый цикл, а запишется только каждые 10 знач в сек.

Не совсем понимаю, перезаписываются, отправляюся последние 10, или первые, или как?
Ладно почитаем мануал.

**Comment by burrbull** [comment]
Еще кое-что вспомнил.
В линуксе есть одна беда, пути к устройствам /dev/ttyUSB0, 1 и т.д. назначаются по мере подключения, и если выдергиваешь шнур, циферка меняется.
Хотелось бы, чтобы была возможность переподключаться к устройству без перезагрузки программы.

**Comment by Tyill** [comment]
тогда ссылку на свой проект добавьте потом (в README на главной можете написать), чтобы люди видели, что есть такой клиент уже.

ну вот, например, по умолчанию стоит отправка пакета каждую секунду, значение в пакет добавляется каждые 100 мс в своем отдельном потоке. Соответственно пользователь пишет в своем рабочем потоке пусть 1 значение в 1 мс, за 100 мс он обновит переменную 100 раз, только в пакет попадет последнее значение, которое он записал. Секунда прошла, в пакете скопилось 10 значений, которые полетели на сервер.

**Comment by Tyill** [comment]
/dev/ttyUSB0 - про это дело подумаю посмотрю, что можно сделать.

**Comment by burrbull** [comment]
Теперь понятнее, спасибо. Прийдется немного переделать.

**Comment by Tyill** [comment]
-по автомасш-ю  добавил кнопку на панель для отключения. 
-значения округлил.  
-на счет инкремента ttACB0, нашел такую [инфу](http://rulinux.net/thread_37638_page_1#msg147628). В общем делается это на уровне ОС.
[версия 104](https://github.com/Tyill/SVisual/releases)

**Comment by burrbull** [comment]
Спасибо, наверное что-то подобное и сделаю.

По поводу масштабирования. Есть еще мысль, для колесика мыши. Можно разделить на гор/верт.
Например при зажатой Ctrl+колесо по вертикали, Shift+колесо по горизонтали. Как в граф. редакторах.

Кстати в сборках есть проблемы с путями, не видит либы:
```
/home/burrbull/Programs/SV/SVMonitor: error while loading shared libraries: libSVGraphPanel.so: cannot open shared object file: No such file or directory
```
Поэтому запускаю через `LD_LIBRARY_PATH`

Клиент я переписал. В принципе уже можно пользоваться. Правда пока не смог сделать, можно было менять размер пакета. Есть один затык.

**Comment by Tyill** [comment]
либы свои все лучше сюда закидывать: /usr/local/lib. спец-но для этого папка сделана. в линуске по умолчанию не ищет рядом либы.

**Comment by burrbull** [comment]
Не, так я точно делать не буду. Так делали в эпоху доисторического материализма.

**Comment by Tyill** [comment]
попробуй. я тоже раньше брезговал. потом начал все в кучу кидать. удобно на самом деле, все в одном месте когда

**Comment by Tyill** [comment]
![2018-10-23 21-43-04](https://user-images.githubusercontent.com/16229799/47376739-d781fd80-d70c-11e8-8fe0-9ee9e7ae8dd0.png)

репу обновил, можете оттуда взять, или сами поправить. 
надо добавить  target_link_libraries(SVAuxFunc uv  pthread)  -  на скрине желтым выделена строка

**Comment by burrbull** [comment]
Похоже там нужен еще QtXlsxWriter. И какой из форков правильный?

**Comment by Tyill** [comment]
QtXlsxWriter его берите из бинарников. 
основная ветка сейчас актуальная.

**Comment by Tyill** [comment]
добавил QtXlsxWriter.so сюда SVisual/linux/Dependences/.
извиняюсь, что не аккуратно все так. скрипт напишу для сборки.

**Comment by Tyill** [comment]
вот этот вот помню брал https://github.com/VSRonin/QtXlsxWriter

**Comment by burrbull** [comment]
На этот раз дошел до:
```
[ 88%] Linking CXX executable ../Builds/SVMonitor
//usr/local/lib/libQtXlsxWriter.so: undefined reference to `QZipReader::FileInfo::FileInfo(QZipReader::FileInfo const&)'
//usr/local/lib/libQtXlsxWriter.so: undefined reference to `QZipReader::FileInfo::~FileInfo()'
collect2: error: ld returned 1 exit status
SVMonitor/CMakeFiles/SVMonitor.dir/build.make:392: recipe for target 'Builds/SVMonitor' failed
make[2]: *** [Builds/SVMonitor] Error 1
CMakeFiles/Makefile2:694: recipe for target 'SVMonitor/CMakeFiles/SVMonitor.dir/all' failed
```
ubuntu 18.04
Qt 5.9.5

**Comment by Tyill** [comment]
попробуйте тогда его отдельно собрать сначала. [этот](https://github.com/VSRonin/QtXlsxWriter)

**Comment by burrbull** [comment]
Нашел. Мой косяк. Не хватало `qtbase5-private-dev`

**Comment by burrbull** [comment]
С исходников собралось.

**Comment by burrbull** [comment]
Допил.

Базовые структуры.
https://github.com/burrbull/svisual-rs

Реализация на UART+DMA для stm32f1
https://github.com/burrbull/svisual-stm32f1

**Comment by Tyill** [comment]
предлагаю статейку написать вам, на хабре пусть, - как все получилось с stm .
с целью продвижения проекта, а то мало кто знает.
