### ISSUE TITLE
proposal for features, potential bugs

### ISSUE THREAD

**Issue by Canonius** [Tyill/SVisual#31]
Hello Alexander,
i am using your application now very frequently. It is very useful!

During the use of 1.1.7 i have some proposals for improvement:
1. Add all channels by right-click on the MODULE to the plot-window (menu on right-click -> add all )
2. Sorting function in the statistics window/table (sort by name, Y1, Y2, MIN, MAX, AVG)
3. auto-save preferences of the Plot-Window (grid-settings, min, max, step, etc) to SVMonitor.ini / SVViewer.ini
4. possibility to reset color presetting in channel of module
![2020-07-15 15_46_41-SVViewer 1 1 7](https://user-images.githubusercontent.com/50411138/87552859-879e5380-c6b2-11ea-85f5-6dae02ca26e9.png)

5. possibility to preset the color with lua script?
```
setFloatValue("PFC_xx_CH08_11", nval, ctm,"#ff0000");
```
6. auto-update of statistics table every second? -> also the sorting
7. predefined lua script of channel has a bug: Offset variable will be added to the time-variable instead of value-variable. Template should be changed
```
ctm = getTimeValue("TC2CAN", "CH08_Temperature"); 
cval = getFloatValue("TC2CAN", "CH08_Temperature");

nval = cval;
offs = 0;

setFloatValue("PFC_xx_CH08_11", nval, ctm + offs); --> offs should be at nval
```
8. add accessible global time-variable that virtual signals can be added. For example a max temperature line. i did it like
```
ctm = getTimeValue("TC2CAN", "CH01_Temperature"); --> variable from CH1, but maybe not always available
setFloatValue("Temp_MAX_120",120, ctm);

to

setFloatValue("Temp_MAX_120",120, time_global);
```
9. I discoverd an issue with loading of script files in SVMonitor & SVViewer
i define/build my lua script in EXCEL and loading it into the application -> it crashes 
i attached the rec file and the lua script -> please remove the .txt in the file name

[svrec_20200714_1610UTC2.dat.txt](https://github.com/Tyill/SVisual/files/4925460/svrec_20200714_1610UTC2.dat.txt)
[TC2CAN-Measurement-Script150720-152019.lua.txt](https://github.com/Tyill/SVisual/files/4925463/TC2CAN-Measurement-Script150720-152019.lua.txt)

I hope you can help!

Thanks in advance & best regards!

**Comment by Canonius** [comment]
Please take your time. Thank you so much for the support! I appreciate it!
Best regards

**Comment by Tyill** [comment]
![Безымянный](https://user-images.githubusercontent.com/16229799/87858212-af591a00-c945-11ea-9d2e-9529e61acfc8.png)

This is what I see after downloading the svrec_20200714_1610UTC2.dat file. 
At what values of 'cycleRecMs' and 'packetSz' recorded?

**Comment by Canonius** [comment]
Hello Alexander,
i am sorry i did not see your email.

cycle is 500ms & 1 packetSz

**Comment by Tyill** [comment]
https://github.com/Tyill/SVisual/releases/tag/1.1.8

**Comment by Tyill** [comment]
corrected one thing
https://github.com/Tyill/SVisual/releases/tag/1.1.8
