### ISSUE TITLE
Перенос сигналов bool в верхнею область окна.

### ISSUE THREAD

**Issue by Alex6305** [Tyill/SVisual#35]
Здравствуйте.
Добавьте пожалуйста, в новой версии программы,  возможность переноса сигналов типа bool в верхнею область этого же окна. В некоторых случаях это улучшит визуальное восприятие графиков.
Заранее спасибо.

**Comment by Tyill** [comment]
Здравствуйте. Хорошо. На выходных может.

**Comment by Tyill** [comment]
А легенду вниз переносить при этом? Иначе будет мешать.

**Comment by Alex6305** [comment]
Легенду сигналов **float** и **int** можно сместить в свободную область окна. 
А для **bool** разместить на соответствующем сигнале, в контрастном к теме цвете, например тема светлая текст чёрный и наоборот.
![Untitled-1](https://user-images.githubusercontent.com/60961110/98861771-e2846380-2476-11eb-8bac-ae9998a1d2b4.jpg)
И если можно, добавьте пожалуйста, hot key для переключения окна графиков в полноэкранный режим и обратно. На ноутбуках с небольшим экраном это будет востребовано.

**Comment by Tyill** [comment]
https://github.com/Tyill/SVisual/releases/tag/1.1.9

Для разворачивания окна в полноэкранный режим можно воспользоваться стандарт сочетанием клавиш:
Win + Up(Down)
