### ISSUE TITLE
sorting function is not right

### ISSUE THREAD

**Issue by Canonius** [Tyill/SVisual#65]
Hello Alex,
in Version 120 i have the issue that values with 3 digits do not sort the right way along with 2 digit values. See in attachment

Thank you very much!

Best regards!

![image](https://user-images.githubusercontent.com/50411138/213183843-6a331b53-0f67-4260-ade2-4dff259afb70.png)

**Comment by Tyill** [comment]
https://github.com/Tyill/SVisual/releases/tag/1.2.1

**Comment by Canonius** [comment]
Hello Alex,
this sorting issue is still there

![image](https://github.com/Tyill/SVisual/assets/50411138/3004c3cf-ab23-444c-a440-23478ad2fbef)

**Comment by Canonius** [comment]
should i make a new issue?

**Comment by Tyill** [comment]
Hello. 
Send a file with records of these signals, I'll take a look at myself

**Comment by Canonius** [comment]
Hello Alex, here are the files.

[svisual.zip](https://github.com/Tyill/SVisual/files/11903479/svisual.zip)

cycleRecMs = 500
packetSz = 1

Thanks a lot!

**Comment by Tyill** [comment]
Fixed it, it seems to be ok now  
[vokoscreen-2023-06-30_11-06-34.zip](https://github.com/Tyill/SVisual/files/11913724/vokoscreen-2023-06-30_11-06-34.zip)

Download the release again  
https://github.com/Tyill/SVisual/releases/tag/1.2.1

**Comment by Canonius** [comment]
I see it in the Video from you. But for example i have a virtual channel as a limit-temperature and this is not sorted along with the others (see screenshots) 

you have the virtual channels in the zip from prev. post

![image](https://github.com/Tyill/SVisual/assets/50411138/78a02126-90c9-48d6-8655-8b9baf6669f1)
![image](https://github.com/Tyill/SVisual/assets/50411138/6b48c081-ba57-4bb7-b0c8-62ad4d7e9ea1)

**Comment by Canonius** [comment]
[20230303.zip](https://github.com/Tyill/SVisual/files/11947305/20230303.zip)


here are also Temperatures >100°C

**Comment by Tyill** [comment]
fixed  
https://github.com/Tyill/SVisual/releases/tag/1.2.1.1

**Comment by Canonius** [comment]
Hello Alex, thanks a lot! Sort function is working.
