### ISSUE TITLE
SVViewer crash

### ISSUE THREAD

**Issue by Canonius** [Tyill/SVisual#71]
SV Viewer crashes if i open 4 dat files which belongs together (one measurement)
sometimes it is also crashing if i open only one dat file

and rightclick on Module - "show all"
or 
simply try to show one channel

[20230303.zip](https://github.com/Tyill/SVisual/files/11947261/20230303.zip)

**Comment by Tyill** [comment]
fixed  
https://github.com/Tyill/SVisual/releases/tag/1.2.1.1
