### ISSUE TITLE
SV Viewer not open new dataset

### ISSUE THREAD

**Issue by Canonius** [Tyill/SVisual#72]
1. if i open in SV viewer one dat file - it loads the data
2. if i open in the same instance new dat file - it doesn't load the new data - it simply shows the old loaded data

[20230303.zip](https://github.com/Tyill/SVisual/files/11947279/20230303.zip)

**Comment by Tyill** [comment]
fixed  
https://github.com/Tyill/SVisual/releases/tag/1.2.1.1

You need to double-click on the chart, then the whole will show

**Comment by Canonius** [comment]
It is now loading the new data if i "double-click" on time or click on the compress X-scale button (see screenshot)

![image](https://github.com/Tyill/SVisual/assets/50411138/8e8079f6-932c-4d9a-b6da-65f449a9868e)

**Comment by Canonius** [comment]
Lua Script for virtual channels should be uploaded here
https://github.com/Tyill/SVisual/issues/65

**Comment by Tyill** [comment]
https://github.com/Tyill/SVisual/releases/tag/1.2.1.2
